server:
  port: 9001

spring:
  application:
    name: simviso-base

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
