server:
  port: 9001

spring:
  application:
    name: simviso-base

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://myhome.tmdaq.com:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: youxiangxin
  jpa:
    database: mysql
    show-sql: true